version: '3.8'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always

  kafka:
    image: 'bitnami/kafka:3.5'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      # Use the hostname 'zookeeper' defined in this file
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # Advertised listeners for external connections (your application)
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: always